// Parser by Megan Lucas, Nadia Mahgerefteh and Stars Momodu
import java_cup.runtime.*;
import Lexer.java;

parser code {:

  Boolean syntaxErrors = false;
  Lexer lexer;

  public Parser(Lexer lex) {
    this.lexer = lex;
  } 

  public void syntax_error(Symbol current_token) { report_error(
     "Syntax error at line " + (current_token.left+1) + ", column " + current_token.right, null );
  }
:}

scan with {: return lexer.next_token(); :};

/* -----------------------------------------------------------------------------------------
 * Terminals
 * -----------------------------------------------------------------------------------------
 */
terminal            SEMI, PLUS, MINUS, TIMES, UMINUS, LPAREN, RPAREN;
terminal Integer    NUMBER;        // our scanner provides numbers as integers

/* -----------------------------------------------------------------------------------------
 * Non Terminals
 * -----------------------------------------------------------------------------------------
 */

// ˜Z Program
non terminal        Program;

// Declarations
non terminal        Declaration_function, Declaration_main, Declaration_variable, Declaration_type, Declaration_type_alias;
non terminal        Parameter_function, Parameter_list_function, Parameter_type, Parameter_list_type;

// Function Definitions
non terminal        Func_body, Main_body;

// Statements
non terminal        Statement, Statement_if, Statement_if_else, Statement_loop;

// Expressions
non terminal        Expression, Expression_list, Literal;
non terminal        Expression_boolean, Expression_comparison, Expression_numeric, Expression_sequence;
non terminal        Expression_function_call, Expression_field_reference;
non terminal        Expression_IO, Expression_read, Expression_write;

// Types
non terminal        Type, Type_primitive, Type_aggregate, Type_defined; // defined type includes aliases
non terminal        Type_dictionary, Type_sequence;
non terminal        Type_legal_dictionary_key, Type_legal_dictionary_value, Type_legal_sequence_value;
non terminal        Type_string;




/* -----------------------------------------------------------------------------------------
 * Precedences
 * -----------------------------------------------------------------------------------------
 */
precedence left PLUS, MINUS;
precedence left TIMES;
precedence left UMINUS;

/* -----------------------------------------------------------------------------------------
 * Rules
 * -----------------------------------------------------------------------------------------
 */

expr_list ::= expr_list expr:e SEMI         {: System.out.println(e);:}
            | expr:e SEMI                   {: System.out.println(e);:}
;
expr      ::= expr:e1 PLUS  expr:e2         {: RESULT = e1+e2;       :}
             | expr:e1 MINUS expr:e2        {: RESULT = e1-e2;       :}
             | expr:e1 TIMES expr:e2        {: RESULT = e1*e2;       :}
             | MINUS expr:e                 {: RESULT = -e;          :}
  	     %prec UMINUS
       | LPAREN expr:e RPAREN	         {: RESULT = e;           :}
       | NUMBER:n	                     {: RESULT = n;           :}
             ;
























             