
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEQ = 39;
  public static final int DIVIDE = 57;
  public static final int LIT_POS_INT = 42;
  public static final int POWER = 58;
  public static final int ASSIGNMENT = 64;
  public static final int CONCAT = 60;
  public static final int POOL = 27;
  public static final int LIT_FLOAT = 45;
  public static final int LIT_NEG_INT = 43;
  public static final int NOT_EQUAL = 63;
  public static final int MINUS = 55;
  public static final int BRACKET_SR = 8;
  public static final int LIT_RAT = 46;
  public static final int AND = 51;
  public static final int NOT = 50;
  public static final int SEMICOLON = 13;
  public static final int BRACKET_SL = 7;
  public static final int ANGLE_R = 9;
  public static final int TYPE_STR = 37;
  public static final int NOP = 49;
  public static final int IN = 59;
  public static final int OR = 52;
  public static final int TDEF = 19;
  public static final int COMMA = 16;
  public static final int ANGLE_L = 10;
  public static final int IMPLIES = 53;
  public static final int FI = 23;
  public static final int TYPE_INT = 33;
  public static final int MULTIPLY = 56;
  public static final int PLUS = 54;
  public static final int LOOP = 26;
  public static final int MAIN = 21;
  public static final int IF = 22;
  public static final int DOT = 15;
  public static final int ID = 3;
  public static final int BRACKET_R = 6;
  public static final int EOF = 0;
  public static final int RETURN = 28;
  public static final int EQUAL = 62;
  public static final int BRACKET_L = 5;
  public static final int error = 1;
  public static final int LIT_STRING = 47;
  public static final int LESS_OR_EQ = 61;
  public static final int NULL = 48;
  public static final int LIT_CHAR = 44;
  public static final int BREAK = 29;
  public static final int CURLY_R = 11;
  public static final int FDEF = 20;
  public static final int TYPE_RAT = 35;
  public static final int TYPE_FLOAT = 34;
  public static final int ERROR = 2;
  public static final int TOP = 40;
  public static final int TYPE_CHAR = 36;
  public static final int CURLY_L = 12;
  public static final int COLON = 14;
  public static final int QUES_MARK = 17;
  public static final int DICT = 38;
  public static final int ELSE = 25;
  public static final int READ = 30;
  public static final int THEN = 24;
  public static final int DOT_LEN = 4;
  public static final int LIT_BOOL = 41;
  public static final int ALIAS = 18;
  public static final int TYPE_BOOL = 32;
  public static final int PRINT = 31;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ERROR",
  "ID",
  "DOT_LEN",
  "BRACKET_L",
  "BRACKET_R",
  "BRACKET_SL",
  "BRACKET_SR",
  "ANGLE_R",
  "ANGLE_L",
  "CURLY_R",
  "CURLY_L",
  "SEMICOLON",
  "COLON",
  "DOT",
  "COMMA",
  "QUES_MARK",
  "ALIAS",
  "TDEF",
  "FDEF",
  "MAIN",
  "IF",
  "FI",
  "THEN",
  "ELSE",
  "LOOP",
  "POOL",
  "RETURN",
  "BREAK",
  "READ",
  "PRINT",
  "TYPE_BOOL",
  "TYPE_INT",
  "TYPE_FLOAT",
  "TYPE_RAT",
  "TYPE_CHAR",
  "TYPE_STR",
  "DICT",
  "SEQ",
  "TOP",
  "LIT_BOOL",
  "LIT_POS_INT",
  "LIT_NEG_INT",
  "LIT_CHAR",
  "LIT_FLOAT",
  "LIT_RAT",
  "LIT_STRING",
  "NULL",
  "NOP",
  "NOT",
  "AND",
  "OR",
  "IMPLIES",
  "PLUS",
  "MINUS",
  "MULTIPLY",
  "DIVIDE",
  "POWER",
  "IN",
  "CONCAT",
  "LESS_OR_EQ",
  "EQUAL",
  "NOT_EQUAL",
  "ASSIGNMENT"
  };
}

